global:
  resolve_timeout: 5m
route:
  receiver: webhook
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h
  group_by: [alertname]
  routes:
  - receiver: webhook
    group_wait: 10s
    match:
      team: node
receivers:
- name: webhook
  webhook_configs:
  - url: 'https://open.feishu.cn/open-apis/bot/v2/hook/d170c210-843c-4ee8-af8d-93abd0e28393'
    send_resolved: true
# - name: email
#   email_configs:
#   - to: 1215007121@qq.com