version: '3'
services:
  prometheus:
    logging:
      driver: 'json-file'
      options:
        max-size: '50m'
    image: prom/prometheus
    user: 'root'
    restart: always
    volumes:
      - ./prometheus_data:/prometheus_data:rw
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./targets.json:/etc/prometheus/targets.json
      - ./rules.yml:/etc/prometheus/rules.yml
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command:
      - '--storage.tsdb.path=/prometheus_data'
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.retention=24h' # 保留时间,默认为15天
      - '--web.enable-lifecycle' # 可以热更新配置
      - '--storage.tsdb.retention.size=512MB' # 最多保存的数据大小
    ports:
      - '9090:9090'
  alertmanager:
    image: prom/alertmanager
    volumes:
      - ./alertmanager.yml:/etc/alertmanager/alertmanager.yml
    ports:
      - '9093:9093'
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'

  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter
    command:
      - '--path.rootfs=/host'
#    network_mode: host
    pid: host
    ports:
      - "9100:9100"
    volumes:
      - '/:/host:ro,rslave'
  grafana:
      image: grafana/grafana:10.2.2
      volumes:
         - ./grafana-datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
      environment:
        - GF_AUTH_ANONYMOUS_ENABLED=true
        - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
        - GF_AUTH_DISABLE_LOGIN_FORM=true
#        - GF_FEATURE_TOGGLES_ENABLE=flameGraph traceqlSearch correlations traceQLStreaming metricsSummary traceqlEditor
      ports:
        - "3000:3000"

