global:
  scrape_interval: 15s # 抓取频率，默认1分钟
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
scrape_configs:
#  - job_name: 'midway_project'
#    file_sd_configs:
#      - refresh_interval: 1m
#        files:
#          - '/etc/prometheus/targets.json'
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  # - job_name: "dockerswarm"
  #   dockerswarm_sd_configs:
  #     - host: unix:///var/run/docker.sock # You can also use http/https to connect to the Docker daemon.
  #       role: tasks
  #   relabel_configs:
  #     # Only keep containers that should be running.
  #     - source_labels: [__meta_dockerswarm_task_desired_state]
  #       regex: running
  #       action: keep
  - job_name: "node_export"
    static_configs:
      - targets: ["node_exporter:9100"]
  - job_name: "pushgateway"
    honor_labels: true # 很重要
    static_configs:
      - targets: [ "pushgateway:9091" ]

alerting:
  alertmanagers:
    - static_configs:
      - targets: ["alertmanager:9093"]
rule_files:
    - /etc/prometheus/rules.yml
